name: Publish Docker Images

on:
  push:
    branches:
      - "release/*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      - name: Check Version
        uses: ./.github/actions/check-version

  publish-ng-serve-image:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Install Node & Dependencies
        uses: ./.github/actions/setup-node

      - name: Publish
        uses: ./.github/actions/publish-docker-image
        with:
          image: ng-serve

  publish-ng-sdk-image:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Install Node & Dependencies
        uses: ./.github/actions/setup-node

      - name: Publish
        uses: ./.github/actions/publish-docker-image
        with:
          image: ng-sdk

  publish-dom-config:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Install Node & Dependencies
        uses: ./.github/actions/setup-node

      - name: Build
        uses: ./.github/actions/build

      - name: Pack
        uses: ./.github/actions/pack

      - name: Publish
        uses: ./.github/actions/publish-node-package
        with:
          toGithub: true
          toNpm: true
          npmToken: ${{ secrets.NPM_TOKEN  }}

  create-release:
    runs-on: ubuntu-latest
    needs: [publish-ng-serve-image, publish-ng-sdk-image, publish-dom-config]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Create Release
        uses: ./.github/actions/create-release
